/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.swing.Panel;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author lelopez
 */
public class PanelImagen extends javax.swing.JPanel {

    ImageIcon imageIcon;
    String rutaArchivo;

    /**
     * Creates new form NewJPanel
     */
    public PanelImagen() {
        initComponents();

    }

    public PanelImagen(ImageIcon img) {
        initComponents();

    }

    public PanelImagen(String ruta) {
        // "/img/logoAldPlus.png"
        this.rutaArchivo = ruta;
        imageIcon = new ImageIcon(getClass().getResource(rutaArchivo));
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public ImageIcon getImageIcon() {
        return imageIcon;
    }

    public void setImageIcon(ImageIcon imageIcon) {
        this.imageIcon = imageIcon;
    }

    public void setImageIcon(String ruta) {
        imageIcon = new ImageIcon(getClass().getResource(ruta));
        repaint();

    }

    @Override
    protected void paintComponent(Graphics gra) {
        Dimension height = getSize();
        try {
//Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
           
//se dibuja la imagen que tenemos en el paquete Images //dentro de un panel

            gra.drawImage(imageIcon.getImage(), 0, 0, height.width, height.height, null);
        } catch (Exception e) {

        }

        setOpaque(false);
        super.paintComponent(gra);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
