/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GPS.PuntosGps;

import GPS.wayPoints.MyWayPoint;
import GPS.wayPoints.WayPointRenderer;
import com.conf.Inicio;
import com.obj.dist.CManifiestosDeDistribucion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.MouseInputListener;
import org.jxmapviewer.*;
import org.jxmapviewer.input.PanKeyListener;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.painter.Painter;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.TileFactoryInfo;
import org.jxmapviewer.viewer.WaypointPainter;

/**
 *
 * @author Usuario
 */
public class PuntosGps extends javax.swing.JInternalFrame {

    public boolean verificado;

    Carro carro = null;
    //List<MyWayPoint> c;
    //List<MyWayPoint> wpPuntosRecorridos;

    Set<MyWayPoint> listaWpClientes;
    Set<MyWayPoint> listaWpPuntosRecorridos;

    List<Painter<JXMapViewer>> painters;

    List<Carro> listadeCarros;
    List<PolyLine> listadeLineas;
    String placa;

    String fechaInicial, fechaFinal;

    GeoPosition centro;
    GeoPosition puntoCliente;

    private List<ImageIcon> listaDeIconosClientes;

    String servertime = "";
    String servertime2 = "9";

    String fechaDistribucion = "";

    Inicio ini;

    //private FResidentes residente = (FResidentes)this.getParent();//
    /**
     * Creates new form FBuscar2
     */
    public PuntosGps(Inicio ini) {  // av 3 # 10-53 multipagas  

        this.ini = ini;
        initComponents();
       jFechaFinal.setVisible(false);
       jFechaInicial.setVisible(false);
       lblDesde.setVisible(false);
       lblHasta.setVisible(false);

        // Obteniendo la fecha actual del sistema.
        Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
        Calendar calendario = Calendar.getInstance();
        int hora = calendario.getTime().getHours();
        int minuto = calendario.getTime().getMinutes();
        int segundo = calendario.getTime().getSeconds();

        GregorianCalendar gc = new GregorianCalendar();

        long minIni = gc.getTimeInMillis() - ((3600000 * hora) + (60000 * minuto) + (1000 * segundo));
        long minMax = gc.getTimeInMillis();

        jFechaInicial.setDate(new Date(minIni));

        jFechaFinal.setDate(new Date(minMax));

        painters = new ArrayList<Painter<JXMapViewer>>();

        jCheckRecorrido.setEnabled(true);

        SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-dd");
        SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        fechaDistribucion = formatter.format(jFechaInicial.getDate());

        fechaInicial = Formato.format(jFechaInicial.getDate());
        fechaFinal = Formato.format(jFechaFinal.getDate());


        /*
        String cadenaDeConexion = String.format("jdbc:mysql://%s/%s?%s%s",
        "190.144.23.186",
        "rutero",
        "useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota",
        "&useSSL=false");**/
        //  connServidorRuta = DriverManager.getConnection(cadenaDeConexion, "luislopez", "jslslpzmjc1212");
        /*
        cadenaDeConexion = String.format("jdbc:mysql://%s/%s?%s%s",
        "129.151.107.181",
        "traccar",
        "useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota",
        "&useSSL=false");
        connServidorGps = DriverManager.getConnection(cadenaDeConexion, "luislopez", "%jslslpzmjC12%");
        **/
        init();
        iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMapa = new javax.swing.JPanel();
        jXMapViewer1 = new org.jxmapviewer.JXMapViewer();
        comboMap = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCheckRecorrido = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaDeCarros = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        lblDesde = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        jFechaFinal = new com.toedter.calendar.JDateChooser();
        jFechaInicial = new com.toedter.calendar.JDateChooser();
        txtCoordenadas = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Formulario para Consulta de Rutas, clientes y vehiculos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/img16x16/map.png"))); // NOI18N

        jXMapViewer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXMapViewer1MouseClicked(evt);
            }
        });

        comboMap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Virtual Earth", "Open Street MAp", "Hybrid", "Satellite" }));
        comboMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMapActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setOpaque(false);

        jCheckRecorrido.setText("Recorrido");
        jCheckRecorrido.setEnabled(false);
        jCheckRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRecorridoActionPerformed(evt);
            }
        });

        jPanel3.setOpaque(false);

        jListaDeCarros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListaDeCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaDeCarrosMouseClicked(evt);
            }
        });
        jListaDeCarros.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaDeCarrosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaDeCarros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCheckRecorrido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setOpaque(false);

        lblDesde.setText("Desde  :");

        lblHasta.setText("Hasta :");

        jFechaFinal.setToolTipText("Seleccionar la fecha ");
        jFechaFinal.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        jFechaFinal.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jFechaInicial.setToolTipText("Seleccionar la fecha ");
        jFechaInicial.setDateFormatString("yyyy-MM-dd HH:mm:ss");
        jFechaInicial.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHasta)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesde)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFechaInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(jFechaFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblDesde)
                .addGap(1, 1, 1)
                .addComponent(jFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCoordenadas.setEditable(false);
        txtCoordenadas.setText("jjjj");
        txtCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoordenadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXMapViewer1Layout = new javax.swing.GroupLayout(jXMapViewer1);
        jXMapViewer1.setLayout(jXMapViewer1Layout);
        jXMapViewer1Layout.setHorizontalGroup(
            jXMapViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewer1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jXMapViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 698, Short.MAX_VALUE)
                .addComponent(comboMap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jXMapViewer1Layout.setVerticalGroup(
            jXMapViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXMapViewer1Layout.createSequentialGroup()
                .addGroup(jXMapViewer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMapaLayout = new javax.swing.GroupLayout(panelMapa);
        panelMapa.setLayout(panelMapaLayout);
        panelMapaLayout.setHorizontalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMapViewer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMapaLayout.setVerticalGroup(
            panelMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXMapViewer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMapActionPerformed
        TileFactoryInfo info = null;

        int index = comboMap.getSelectedIndex();
        switch (index) {
            case 0:
                info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.MAP);
                break;
            case 1:
                info = new OSMTileFactoryInfo();
                break;
            case 2:
                info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.HYBRID);
                break;
            case 3:
                info = new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.SATELLITE);
                break;

            default:

                break;

        }

        DefaultTileFactory tileFactory = new DefaultTileFactory(info);
        jXMapViewer1.setTileFactory(tileFactory);

    }//GEN-LAST:event_comboMapActionPerformed

    private void jCheckRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRecorridoActionPerformed

        if (jCheckRecorrido.isSelected()) {
            /* Date fecha = new Date(Calendar.getInstance().getTimeInMillis());
            
            String fechaTexto = formatter.format(fecha);
            fechaDistribucion = fechaTexto;

           **/
            SimpleDateFormat formatter = new SimpleDateFormat("YYYY-MM-dd");
            SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            servertime = Formato.format(jFechaInicial.getDate());
            servertime2 = Formato.format(jFechaFinal.getDate());

            fechaDistribucion = formatter.format(jFechaInicial.getDate());

            new Thread(new HiloPuntosGps(this, "mostrarRecorrido", placa)).start();
        }
        txtCoordenadas.setText("");
    }//GEN-LAST:event_jCheckRecorridoActionPerformed

    private void jListaDeCarrosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaDeCarrosValueChanged


    }//GEN-LAST:event_jListaDeCarrosValueChanged

    private void jXMapViewer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXMapViewer1MouseClicked
        GeoPosition geoposition = jXMapViewer1.convertPointToGeoPosition(evt.getPoint());
        txtCoordenadas.setText(geoposition.getLatitude() + "," + geoposition.getLongitude());

    }//GEN-LAST:event_jXMapViewer1MouseClicked

    private void jListaDeCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaDeCarrosMouseClicked

        placa = jListaDeCarros.getSelectedValue().toString();
//        for(Carro car : listadeCarros){
//            if(car.getPlaca().equals(placa)){
//                this.carro = car;
//                break;
//            }
//            
//        }
        txtCoordenadas.setText("");

        llamarClientesDePlaca();
    }//GEN-LAST:event_jListaDeCarrosMouseClicked

    private void txtCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoordenadasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMap;
    public javax.swing.JCheckBox jCheckRecorrido;
    public com.toedter.calendar.JDateChooser jFechaFinal;
    public com.toedter.calendar.JDateChooser jFechaInicial;
    public javax.swing.JList<String> jListaDeCarros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public org.jxmapviewer.JXMapViewer jXMapViewer1;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JPanel panelMapa;
    public javax.swing.JTextField txtCoordenadas;
    // End of variables declaration//GEN-END:variables

    private void init() {

        /*se establece la ubicacion del cliente */
        Double coordenadas;
        String punto = ini.getGeoPositionCliente();
        String[] coord = punto.split(",");
        puntoCliente = new GeoPosition(Double.parseDouble(coord[0]), Double.parseDouble(coord[1]));

        TileFactoryInfo info = new OSMTileFactoryInfo();
        DefaultTileFactory tileFactory = new DefaultTileFactory(info);
        jXMapViewer1.setTileFactory(tileFactory);
        // GeoPosition geo = new GeoPosition(7.917701, -72.53558);
        jXMapViewer1.setAddressLocation(puntoCliente);
        jXMapViewer1.setZoom(5);
        jXMapViewer1.setSize(getSize());

        // Crear los eventos del mouse
        MouseInputListener ml = new PanMouseInputListener(jXMapViewer1);
        jXMapViewer1.addMouseListener(ml);
        jXMapViewer1.addMouseMotionListener(ml);
        jXMapViewer1.addMouseWheelListener(new ZoomMouseWheelListenerCenter(jXMapViewer1));
        jXMapViewer1.addKeyListener(new PanKeyListener(jXMapViewer1));
        jXMapViewer1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {

                boolean right = SwingUtilities.isRightMouseButton(evt);
                if (right) {
                    JOptionPane.showMessageDialog(jXMapViewer1, "punto de la pantalla" + evt.getLocationOnScreen());
                }
            }
        });

    }

    public void initWayPointsClientes() {
        WaypointPainter<MyWayPoint> wp = new WayPointRenderer();
        wp.setWaypoints(listaWpClientes);
        jXMapViewer1.setOverlayPainter(wp);
        for (MyWayPoint d : listaWpClientes) {
            jXMapViewer1.add(d.getButton());

        }

    }

    private void clearWayPoints() {
        for (MyWayPoint d : listaWpClientes) {
            jXMapViewer1.remove(d.getButton());

        }
        listaWpClientes.clear();
        //initWayPoints();
    }

    private void iniciar() {
        // llena una lista con los iconos de los clientes
        new Thread(new HiloPuntosGps(this, "setListaDeIconos")).start();

        //  setListaDeCarros(true);
    }

    public void setListaDeCarros() {
        Thread thListadeVehiculos = new Thread(new Runnable() {
            @Override
            public void run() {

                ResultSet rst = null;
                Statement st = null;
                Connection con, con2 = null;
                String sql = "";
                //String fechaDistribucion = "2022-06-21";

                con = ini.getConnRemota();
                con2 = ini.getConnGPS();

                try {

                    sql = "SELECT DISTINCT vehiculo, nombresConductor "
                            + "FROM rutero "
                            + "WHERE "
                            + "fechaDistribucion='" + fechaDistribucion + "'"
                            + "order by vehiculo asc; "; //and estadoManifiesto='" + estadoManifiesto + "'";

                    if (con != null) {
                        listadeCarros = new ArrayList<>();
                        st = con.createStatement();
                        rst = st.executeQuery(sql);

                        int i = 0;
                        while (rst.next()) {
                            Carro car = new Carro(con, con2);
                            car.setPlaca(rst.getString("vehiculo"));
                            car.setConductor(rst.getString("nombresConductor"));
                            car.setIcon(listaDeIconosClientes.get(i++));
                            car.setFechaDeInicio(servertime);
                            car.setFechaFinal(servertime2);
                            car.setFechaDistribucion(fechaDistribucion);
                            listadeCarros.add(car);

                            if (i == 17) {
                                i = 0;
                            }

//                    if(width < (java.awt.Toolkit.getDefaultToolkit().getScreenSize().width-20)){
//                         width+=27;
//                    }
                        }

                        rst.close();
                        st.close();
                        //con.close();

                        llenarJlistaVehiculos();

                        cargarClientesPorCarro();

                    }

                } catch (SQLException ex) {
                    Logger.getLogger(PuntosGps.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
        thListadeVehiculos.start();
    }

    public void setListaDeCarros(boolean c) {
        Thread thListadeVehiculos = new Thread(new Runnable() {
            @Override
            public void run() {

                String sql = "";
                //String fechaDistribucion = "2022-06-21";

                listadeCarros = new ArrayList<>();
                int i = 0;

                for (CManifiestosDeDistribucion man : ini.getListaDeManifiestossinDescargar()) {
                    Carro car = new Carro(ini);
                    car.setPlaca(man.getVehiculo());
                    car.setConductor(man.getNombreConductor() + " " + man.getApellidosConductor());//rst.getString("nombresConductor"));
                    car.setIcon(listaDeIconosClientes.get(i++));
                    car.setFechaDeInicio(servertime);
                    car.setFechaFinal(servertime2);
                    car.setFechaDistribucion(fechaDistribucion);
                    listadeCarros.add(car);

                    if (i == 17) {
                        i = 0;
                    }

//                    if(width < (java.awt.Toolkit.getDefaultToolkit().getScreenSize().width-20)){
//                         width+=27;
//                    }
                }

                llenarJlistaVehiculos();

                cargarClientesPorCarro();

            }

        });
        thListadeVehiculos.start();
    }

    private void llenarJlistaVehiculos() {

        if (listadeCarros != null || !listadeCarros.isEmpty()) {
            DefaultListModel modelo = new DefaultListModel();
            for (Carro car : listadeCarros) {
                modelo.addElement(car.getPlaca());
            }

            jListaDeCarros.setModel(modelo);
        }

    }

    private void cargarClientesPorCarro() {

        Thread thPedidosDelDia = new Thread(new Runnable() {
            @Override
            public void run() {

                for (Carro car : listadeCarros) {
                    // new Thread(new HiloPuntosGps(PuntosGps.this, "cargarClientesPorCarro"), car.getPlaca()).start();
                    if (car.getWpClientes() == null) {
                        car.ini = ini;
                        car.setWpClientes(car.getImageIcon());
                    }

                }

            }

        });
        thPedidosDelDia.start();

    }

    public List<ImageIcon> getListaDeIconos() {
        return listaDeIconosClientes;
    }

    public void setListaDeIconos(List<ImageIcon> listaDeIconos) {
        this.listaDeIconosClientes = listaDeIconos;
    }

    public void llamarClientesDePlaca() {
        jCheckRecorrido.setEnabled(false);
        jCheckRecorrido.setSelected(false);
        new Thread(new HiloPuntosGps(this, "putWayPointsClientes", placa)).start();

    }

}
